routes/web.php
<?php

Route::redirect('/', '/login');

// Horarios
Route::resource('schedule' , 'ScheduleController');

Route::get('/home', function () {
    $user = Auth::user();
    $roles = $user->roles()->get();
    foreach ($roles as $role) {
        //Jugador
        if ($role->pivot->role_id == 4)
        {
            if (session('status')) {
                return redirect()->route('player.home')->with('status', session('status'));
            }

            return redirect()->route('player.home');
        }
    }
        if (session('status')) {
            return redirect()->route('admin.home')->with('status', session('status'));
        }

        return redirect()->route('admin.home');
});

Auth::routes();
Route::get('userVerification/{token}', 'UserVerificationController@approve')->name('userVerification');

Route::get('sharedplayer/{player}', 'ShareController@getPlayer')->name('sharedplayer');

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'adminroute']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Questions
    Route::delete('questions/destroy', 'QuestionsController@massDestroy')->name('questions.massDestroy');
    Route::resource('questions', 'QuestionsController');
    
    // Clubs
    Route::delete('clubs/destroy', 'ClubsController@massDestroy')->name('clubs.massDestroy');
    Route::post('clubs/parse-csv-import', 'ClubsController@parseCsvImport')->name('clubs.parseCsvImport');
    Route::post('clubs/process-csv-import', 'ClubsController@processCsvImport')->name('clubs.processCsvImport');
    Route::resource('clubs', 'ClubsController');

    // Tournaments
    Route::delete('tournaments/destroy', 'TournamentsController@massDestroy')->name('tournaments.massDestroy');
    Route::post('tournaments/parse-csv-import', 'TournamentsController@parseCsvImport')->name('tournaments.parseCsvImport');
    Route::post('tournaments/process-csv-import', 'TournamentsController@processCsvImport')->name('tournaments.processCsvImport');
    Route::resource('tournaments', 'TournamentsController');

    // Players
    Route::delete('players/destroy', 'PlayersController@massDestroy')->name('players.massDestroy');
    Route::post('players/parse-csv-import', 'PlayersController@parseCsvImport')->name('players.parseCsvImport');
    Route::post('players/process-csv-import', 'PlayersController@processCsvImport')->name('players.processCsvImport');
    Route::resource('players', 'PlayersController');

    // Scores
    Route::delete('scores/destroy', 'ScoresController@massDestroy')->name('scores.massDestroy');
    Route::post('scores/parse-csv-import', 'ScoresController@parseCsvImport')->name('scores.parseCsvImport');
    Route::post('scores/process-csv-import', 'ScoresController@processCsvImport')->name('scores.processCsvImport');
    Route::resource('scores', 'ScoresController');

    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');

   
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

Route::group(['prefix' => 'player', 'as' => 'player.', 'namespace' => 'Player', 'middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('linkplayer/{id}', 'HomeController@getLinkPlayer')->name('linkplayer');
    Route::get('firstquestionary', 'HomeController@getFirstQuestionary')->name('firstquestionary');
    Route::post('firstquestionary', 'HomeController@postFirstQuestionary')->name('savefirstquestionary');
    Route::post('saveuserlocation', 'HomeController@postSaveUserLocation')->name('saveuserlocation');

    Route::get('player/{id}', 'PlayersController@getPlayer')->name('player');
    Route::get('myplayer', 'PlayersController@getMyPlayer')->name('myplayer');
    Route::post('myprofile', 'PlayersController@postMyProfile')->name('savemyprofile');

    Route::get('playerinfo/{player}', 'PlayersController@getPlayerinfo')->name('playerinfo');
    
    Route::get('searchplayers', 'HomeController@getSearchPlayers')->name('getsearchplayers');
    Route::post('searchplayers', 'HomeController@postSearchPlayers')->name('searchplayers');
    Route::post('search', 'HomeController@search')->name('search');

    // Clubs
    Route::delete('clubs/destroy', 'ClubsController@massDestroy')->name('clubs.massDestroy');
    Route::resource('clubs', 'ClubsController');

    // Tournaments
    Route::delete('tournaments/destroy', 'TournamentsController@massDestroy')->name('tournaments.massDestroy');
    Route::resource('tournaments', 'TournamentsController');

    // Players
    Route::delete('players/destroy', 'PlayersController@massDestroy')->name('players.massDestroy');
    Route::resource('players', 'PlayersController');

    // Scores
    Route::delete('scores/destroy', 'ScoresController@massDestroy')->name('scores.massDestroy');
    Route::get('scores/verify/{score}', 'ScoresController@getVerifyScore')->name('scores.verify');
    Route::get('scores/confirmunverify/{score}', 'ScoresController@getConfirmUnverifyScore')->name('scores.confirmunverify');
    Route::get('scores/confirmverify/{score}', 'ScoresController@getConfirmVerifyScore')->name('scores.confirmverify');
    Route::resource('scores', 'ScoresController');

    //Messenger
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');

    Route::get('messenger/conversation/{player}', 'MessengerController@getConversation')->name('messenger.conversation');
});

app/Models/Tournament.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class Tournament extends Model
{
    use SoftDeletes;

    public $table = 'tournaments';

    protected $dates = [
        'startdate',
        'enddate',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'startdate',
        'enddate',
        'mens',
        'womens',
        'mix',
        'city',
        'club_id',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function tournamentScores()
    {
        return $this->hasMany(Score::class, 'tournament_id', 'id');
    }

    public function getStartdateAttribute($value)
    {
        return $value ? Carbon::parse($value)->format(config('panel.date_format')) : null;
    }

    public function setStartdateAttribute($value)
    {
        $this->attributes['startdate'] = $value ? Carbon::createFromFormat(config('panel.date_format'), $value)->format('Y-m-d') : null;
    }

    public function getEnddateAttribute($value)
    {
        return $value ? Carbon::parse($value)->format(config('panel.date_format')) : null;
    }

    public function setEnddateAttribute($value)
    {
        $this->attributes['enddate'] = $value ? Carbon::createFromFormat(config('panel.date_format'), $value)->format('Y-m-d') : null;
    }

    public function club()
    {
        return $this->belongsTo(Club::class, 'club_id');
    }
}

app/Http/Controllers/Admin/TournamentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyTournamentRequest;
use App\Http\Requests\StoreTournamentRequest;
use App\Http\Requests\UpdateTournamentRequest;
use App\Models\Club;
use App\Models\Tournament;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class TournamentsController extends Controller
{
    use CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('tournament_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = Tournament::with(['club'])->select(sprintf('%s.*', (new Tournament)->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate      = 'tournament_show';
                $editGate      = 'tournament_edit';
                $deleteGate    = 'tournament_delete';
                $crudRoutePart = 'tournaments';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : "";
            });
            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : "";
            });

            $table->editColumn('mens', function ($row) {
                return '<input type="checkbox" disabled ' . ($row->mens ? 'checked' : null) . '>';
            });
            $table->editColumn('womens', function ($row) {
                return '<input type="checkbox" disabled ' . ($row->womens ? 'checked' : null) . '>';
            });
            $table->editColumn('mix', function ($row) {
                return '<input type="checkbox" disabled ' . ($row->mix ? 'checked' : null) . '>';
            });
            $table->editColumn('city', function ($row) {
                return $row->city ? $row->city : "";
            });
            $table->addColumn('club_name', function ($row) {
                return $row->club ? $row->club->name : '';
            });

            $table->editColumn('club.indoor_courts', function ($row) {
                return $row->club ? (is_string($row->club) ? $row->club : $row->club->indoor_courts) : '';
            });
            $table->editColumn('club.outdor_courts', function ($row) {
                return $row->club ? (is_string($row->club) ? $row->club : $row->club->outdor_courts) : '';
            });

            $table->rawColumns(['actions', 'placeholder', 'mens', 'womens', 'mix', 'club']);

            return $table->make(true);
        }

        return view('admin.tournaments.index');
    }

    public function create()
    {
        abort_if(Gate::denies('tournament_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $clubs = Club::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.tournaments.create', compact('clubs'));
    }

    public function store(StoreTournamentRequest $request)
    {
        $tournament = Tournament::create($request->all());

        return redirect()->route('admin.tournaments.index');
    }

    public function edit(Tournament $tournament)
    {
        abort_if(Gate::denies('tournament_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $clubs = Club::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $tournament->load('club');

        return view('admin.tournaments.edit', compact('clubs', 'tournament'));
    }

    public function update(UpdateTournamentRequest $request, Tournament $tournament)
    {
        $tournament->update($request->all());

        return redirect()->route('admin.tournaments.index');
    }

    public function show(Tournament $tournament)
    {
        abort_if(Gate::denies('tournament_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tournament->load('club', 'tournamentScores');

        return view('admin.tournaments.show', compact('tournament'));
    }

    public function destroy(Tournament $tournament)
    {
        abort_if(Gate::denies('tournament_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tournament->delete();

        return back();
    }

    public function massDestroy(MassDestroyTournamentRequest $request)
    {
        Tournament::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/tournaments/relationships/tournamentScores.blade.php
<div class="m-3">
    @can('score_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route('admin.scores.create') }}">
                    {{ trans('global.add') }} {{ trans('cruds.score.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="card">
        <div class="card-header">
            {{ trans('cruds.score.title_singular') }} {{ trans('global.list') }}
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-tournamentScores">
                    <thead>
                        <tr>
                            <th width="10">

                            </th>
                            <th>
                                {{ trans('cruds.score.fields.id') }}
                            </th>
                            <th>
                                {{ trans('cruds.score.fields.tournament') }}
                            </th>
                            <th>
                                {{ trans('cruds.tournament.fields.mens') }}
                            </th>
                            <th>
                                {{ trans('cruds.tournament.fields.womens') }}
                            </th>
                            <th>
                                {{ trans('cruds.tournament.fields.mix') }}
                            </th>
                            <th>
                                {{ trans('cruds.score.fields.team_1_player_1') }}
                            </th>
                            <th>
                                {{ trans('cruds.player.fields.surname') }}
                            </th>
                            <th>
                                {{ trans('cruds.score.fields.team_1_player_2') }}
                            </th>
                            <th>
                                {{ trans('cruds.player.fields.surname') }}
                            </th>
                            <th>
                                {{ trans('cruds.score.fields.team_2_player_1') }}
                            </th>
                            <th>
                                {{ trans('cruds.player.fields.surname') }}
                            </th>
                            <th>
                                {{ trans('cruds.score.fields.team_2_player_2') }}
                            </th>
                            <th>
                                {{ trans('cruds.player.fields.surname') }}
                            </th>
                            <th>
                                {{ trans('cruds.score.fields.set_1_team_1') }}
                            </th>
                            <th>
                                {{ trans('cruds.score.fields.set_1_team_2') }}
                            </th>
                            <th>
                                {{ trans('cruds.score.fields.set_2_team_1') }}
                            </th>
                            <th>
                                {{ trans('cruds.score.fields.set_2_team_2') }}
                            </th>
                            <th>
                                {{ trans('cruds.score.fields.set_3_team_1') }}
                            </th>
                            <th>
                                {{ trans('cruds.score.fields.set_3_team_2') }}
                            </th>
                            <th>
                                &nbsp;
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($scores as $key => $score)
                            <tr data-entry-id="{{ $score->id }}">
                                <td>

                                </td>
                                <td>
                                    {{ $score->id ?? '' }}
                                </td>
                                <td>
                                    {{ $score->tournament->name ?? '' }}
                                </td>
                                <td>
                                    <span style="display:none">{{ $score->tournament->mens ?? '' }}</span>
                                    <input type="checkbox" disabled="disabled" {{ $score->tournament->mens ? 'checked' : '' }}>
                                </td>
                                <td>
                                    <span style="display:none">{{ $score->tournament->womens ?? '' }}</span>
                                    <input type="checkbox" disabled="disabled" {{ $score->tournament->womens ? 'checked' : '' }}>
                                </td>
                                <td>
                                    <span style="display:none">{{ $score->tournament->mix ?? '' }}</span>
                                    <input type="checkbox" disabled="disabled" {{ $score->tournament->mix ? 'checked' : '' }}>
                                </td>
                                <td>
                                    {{ $score->team_1_player_1->name ?? '' }}
                                </td>
                                <td>
                                    {{ $score->team_1_player_1->surname ?? '' }}
                                </td>
                                <td>
                                    {{ $score->team_1_player_2->name ?? '' }}
                                </td>
                                <td>
                                    {{ $score->team_1_player_2->surname ?? '' }}
                                </td>
                                <td>
                                    {{ $score->team_2_player_1->name ?? '' }}
                                </td>
                                <td>
                                    {{ $score->team_2_player_1->surname ?? '' }}
                                </td>
                                <td>
                                    {{ $score->team_2_player_2->name ?? '' }}
                                </td>
                                <td>
                                    {{ $score->team_2_player_2->surname ?? '' }}
                                </td>
                                <td>
                                    {{ $score->set_1_team_1 ?? '' }}
                                </td>
                                <td>
                                    {{ $score->set_1_team_2 ?? '' }}
                                </td>
                                <td>
                                    {{ $score->set_2_team_1 ?? '' }}
                                </td>
                                <td>
                                    {{ $score->set_2_team_2 ?? '' }}
                                </td>
                                <td>
                                    {{ $score->set_3_team_1 ?? '' }}
                                </td>
                                <td>
                                    {{ $score->set_3_team_2 ?? '' }}
                                </td>
                                <td>
                                    @can('score_show')
                                        <a class="btn btn-xs btn-primary" href="{{ route('admin.scores.show', $score->id) }}">
                                            {{ trans('global.view') }}
                                        </a>
                                    @endcan

                                    @can('score_edit')
                                        <a class="btn btn-xs btn-info" href="{{ route('admin.scores.edit', $score->id) }}">
                                            {{ trans('global.edit') }}
                                        </a>
                                    @endcan

                                    @can('score_delete')
                                        <form action="{{ route('admin.scores.destroy', $score->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                        </form>
                                    @endcan

                                </td>

                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('score_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.scores.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-tournamentScores:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection