routes/web.php
<?php

Route::redirect('/', '/login');

// Horarios
Route::resource('schedule' , 'ScheduleController');

Route::get('/home', function () {
    $user = Auth::user();
    $roles = $user->roles()->get();
    foreach ($roles as $role) {
        //Jugador
        if ($role->pivot->role_id == 4)
        {
            if (session('status')) {
                return redirect()->route('player.home')->with('status', session('status'));
            }

            return redirect()->route('player.home');
        }
    }
        if (session('status')) {
            return redirect()->route('admin.home')->with('status', session('status'));
        }

        return redirect()->route('admin.home');
});

Auth::routes();
Route::get('userVerification/{token}', 'UserVerificationController@approve')->name('userVerification');

Route::get('sharedplayer/{player}', 'ShareController@getPlayer')->name('sharedplayer');

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'adminroute']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Questions
    Route::delete('questions/destroy', 'QuestionsController@massDestroy')->name('questions.massDestroy');
    Route::resource('questions', 'QuestionsController');
    
    // Clubs
    Route::delete('clubs/destroy', 'ClubsController@massDestroy')->name('clubs.massDestroy');
    Route::post('clubs/parse-csv-import', 'ClubsController@parseCsvImport')->name('clubs.parseCsvImport');
    Route::post('clubs/process-csv-import', 'ClubsController@processCsvImport')->name('clubs.processCsvImport');
    Route::resource('clubs', 'ClubsController');

    // Tournaments
    Route::delete('tournaments/destroy', 'TournamentsController@massDestroy')->name('tournaments.massDestroy');
    Route::post('tournaments/parse-csv-import', 'TournamentsController@parseCsvImport')->name('tournaments.parseCsvImport');
    Route::post('tournaments/process-csv-import', 'TournamentsController@processCsvImport')->name('tournaments.processCsvImport');
    Route::resource('tournaments', 'TournamentsController');

    // Players
    Route::delete('players/destroy', 'PlayersController@massDestroy')->name('players.massDestroy');
    Route::post('players/parse-csv-import', 'PlayersController@parseCsvImport')->name('players.parseCsvImport');
    Route::post('players/process-csv-import', 'PlayersController@processCsvImport')->name('players.processCsvImport');
    Route::resource('players', 'PlayersController');

    // Scores
    Route::delete('scores/destroy', 'ScoresController@massDestroy')->name('scores.massDestroy');
    Route::post('scores/parse-csv-import', 'ScoresController@parseCsvImport')->name('scores.parseCsvImport');
    Route::post('scores/process-csv-import', 'ScoresController@processCsvImport')->name('scores.processCsvImport');
    Route::resource('scores', 'ScoresController');

    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');

   
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

Route::group(['prefix' => 'player', 'as' => 'player.', 'namespace' => 'Player', 'middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('linkplayer/{id}', 'HomeController@getLinkPlayer')->name('linkplayer');
    Route::get('firstquestionary', 'HomeController@getFirstQuestionary')->name('firstquestionary');
    Route::post('firstquestionary', 'HomeController@postFirstQuestionary')->name('savefirstquestionary');
    Route::post('saveuserlocation', 'HomeController@postSaveUserLocation')->name('saveuserlocation');

    Route::get('player/{id}', 'PlayersController@getPlayer')->name('player');
    Route::get('myplayer', 'PlayersController@getMyPlayer')->name('myplayer');
    Route::post('myprofile', 'PlayersController@postMyProfile')->name('savemyprofile');

    Route::get('playerinfo/{player}', 'PlayersController@getPlayerinfo')->name('playerinfo');
    
    Route::get('searchplayers', 'HomeController@getSearchPlayers')->name('getsearchplayers');
    Route::post('searchplayers', 'HomeController@postSearchPlayers')->name('searchplayers');
    Route::post('search', 'HomeController@search')->name('search');

    // Clubs
    Route::delete('clubs/destroy', 'ClubsController@massDestroy')->name('clubs.massDestroy');
    Route::resource('clubs', 'ClubsController');

    // Tournaments
    Route::delete('tournaments/destroy', 'TournamentsController@massDestroy')->name('tournaments.massDestroy');
    Route::resource('tournaments', 'TournamentsController');

    // Players
    Route::delete('players/destroy', 'PlayersController@massDestroy')->name('players.massDestroy');
    Route::resource('players', 'PlayersController');

    // Scores
    Route::delete('scores/destroy', 'ScoresController@massDestroy')->name('scores.massDestroy');
    Route::get('scores/verify/{score}', 'ScoresController@getVerifyScore')->name('scores.verify');
    Route::get('scores/confirmunverify/{score}', 'ScoresController@getConfirmUnverifyScore')->name('scores.confirmunverify');
    Route::get('scores/confirmverify/{score}', 'ScoresController@getConfirmVerifyScore')->name('scores.confirmverify');
    Route::resource('scores', 'ScoresController');

    //Messenger
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');

    Route::get('messenger/conversation/{player}', 'MessengerController@getConversation')->name('messenger.conversation');
});

app/Http/Controllers/Admin/PlayersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyPlayerRequest;
use App\Http\Requests\StorePlayerRequest;
use App\Http\Requests\UpdatePlayerRequest;
use App\Models\Player;
use App\Models\User;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class PlayersController extends Controller
{
    use CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('player_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = Player::with(['user'])->select(sprintf('%s.*', (new Player)->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate      = 'player_show';
                $editGate      = 'player_edit';
                $deleteGate    = 'player_delete';
                $crudRoutePart = 'players';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : "";
            });
            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : "";
            });
            $table->editColumn('surname', function ($row) {
                return $row->surname ? $row->surname : "";
            });
            $table->editColumn('genre', function ($row) {
                return $row->genre ? Player::GENRE_SELECT[$row->genre] : '';
            });

            $table->editColumn('license_number', function ($row) {
                return $row->license_number ? $row->license_number : "";
            });
            $table->addColumn('user_email', function ($row) {
                return $row->user ? $row->user->email : '';
            });

            $table->rawColumns(['actions', 'placeholder', 'user']);

            return $table->make(true);
        }

        return view('admin.players.index');
    }

    public function create()
    {
        abort_if(Gate::denies('player_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('email', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.players.create', compact('users'));
    }

    public function store(StorePlayerRequest $request)
    {
        $player = Player::create($request->all());

        return redirect()->route('admin.players.index');
    }

    public function edit(Player $player)
    {
        abort_if(Gate::denies('player_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('email', 'id')->prepend(trans('global.pleaseSelect'), '');

        $player->load('user');

        return view('admin.players.edit', compact('users', 'player'));
    }

    public function update(UpdatePlayerRequest $request, Player $player)
    {
        $player->update($request->all());

        return redirect()->route('admin.players.index');
    }

    public function show(Player $player)
    {
        abort_if(Gate::denies('player_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $player->load('user', 'team1Player1Scores', 'team1Player2Scores', 'team2Player1Scores', 'team2Player2Scores');

        return view('admin.players.show', compact('player'));
    }

    public function destroy(Player $player)
    {
        abort_if(Gate::denies('player_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $player->delete();

        return back();
    }

    public function massDestroy(MassDestroyPlayerRequest $request)
    {
        Player::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/Player/ClubsController.php
<?php

namespace App\Http\Controllers\Player;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyClubRequest;
use App\Http\Requests\StoreClubRequest;
use App\Http\Requests\UpdateClubRequest;
use App\Models\Club;
use App\Models\User;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class ClubsController extends Controller
{
    use CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('club_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = Club::with(['users'])->select(sprintf('%s.*', (new Club)->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate      = 'club_show';
                $editGate      = 'club_edit';
                $deleteGate    = 'club_delete';
                $crudRoutePart = 'clubs';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : "";
            });
            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : "";
            });
            $table->editColumn('city', function ($row) {
                return $row->city ? $row->city : "";
            });
            $table->editColumn('indoor_courts', function ($row) {
                return $row->indoor_courts ? $row->indoor_courts : "";
            });
            $table->editColumn('outdor_courts', function ($row) {
                return $row->outdor_courts ? $row->outdor_courts : "";
            });
            $table->editColumn('user', function ($row) {
                $labels = [];

                foreach ($row->users as $user) {
                    $labels[] = sprintf('<span class="label label-info label-many">%s</span>', $user->email);
                }

                return implode(' ', $labels);
            });

            $table->rawColumns(['actions', 'placeholder', 'user']);

            return $table->make(true);
        }

        return view('player.clubs.index');
    }

    public function create()
    {
        abort_if(Gate::denies('club_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('email', 'id');

        return view('player.clubs.create', compact('users'));
    }

    public function store(StoreClubRequest $request)
    {
        $club = Club::create($request->all());
        $club->users()->sync($request->input('users', []));

        return redirect()->route('player.clubs.index');
    }

    public function edit(Club $club)
    {
        abort_if(Gate::denies('club_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('email', 'id');

        $club->load('users');

        return view('player.clubs.edit', compact('users', 'club'));
    }

    public function update(UpdateClubRequest $request, Club $club)
    {
        $club->update($request->all());
        $club->users()->sync($request->input('users', []));

        return redirect()->route('player.clubs.index');
    }

    public function show(Club $club)
    {
        abort_if(Gate::denies('club_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $club->load('users', 'clubTournaments');

        return view('player.clubs.show', compact('club'));
    }

    public function destroy(Club $club)
    {
        abort_if(Gate::denies('club_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $club->delete();

        return back();
    }

    public function massDestroy(MassDestroyClubRequest $request)
    {
        Club::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/player/partials/footer.blade.php
<p>&nbsp;</p>
<p>&nbsp;</p>
<!-- Nav inferior -->
<nav class="botnav fixed-bottom">
  <div class="row" style="margin:0;">
    <div class="col-div-abajo div-abajo">
		<a href="{{ route('player.home') }}"><img class="imagen-abajo mx-auto d-block" src="/resources/home.png" alt="Inicio" title="Inicio"></a>
	</div>
	<div class="col-div-abajo div-abajo">
		<a href="{{ route('player.getsearchplayers') }}"><img class="imagen-abajo mx-auto d-block" src="/resources/lupaAbajo.png" alt=" "></a>
	</div>
	<div class="col-div-abajo div-abajo">
		<a href="{{ route('player.scores.create') }}"><img class="imagen-abajo-mas mx-auto d-block" src="/resources/mas.png" alt="Registrar resultado" title="Registrar resultado"></a>
	</div>
	<div class="col-div-abajo div-abajo">
		<a href="{{ route('player.messenger.showInbox') }}"><img class="imagen-abajo mx-auto d-block" src="/resources/bocadillo.png" alt=" ">
			<?php 
			$userplayer = Auth()->user()->userPlayers()->first();
			if ($userplayer)
				$unreads = $userplayer->unreadTopics();
			else
				$unreads = 0;
			?>
			@if ($unreads>0)
			<span class="unreadmessages">{{ Auth()->user()->userPlayers()->first()->unreadTopics() }}</span>
    		@endif
</a>
	</div>
	<div class="col-div-abajo div-abajo">
		<a href="{{ route('player.myplayer') }}"><img class="imagen-abajo mx-auto d-block" src="/resources/persona.png" alt=" "></a>
	</div>
  </div>
</nav>

resources/views/player/partials/header.blade.php
<!-- Barra superior / buscador -->
<div class="topnav">
  <div class="row">
    <div class="col-3">
    <a href="{{ route('player.home') }}"><img class="logotipo mx-auto d-block" src="/resources/logo.png" alt=" " width="70px" height="70px"></a> 
  </div>
    <div class="col-9" style="background-color:#1B3967; padding: 0; width: 100vw;">
    @can('player_edit')
    <div class="search-container">
      <form action="{{ action('Player\HomeController@search') }}" method="POST">
        @csrf
        <button type="submit"><img src="/resources/lupa.png" alt=" " width="20px" height="25px"></button>
        <input style="outline: none; height: 38px" type="text" placeholder="Buscar jugadores" name="playername" value="{{ isset($playernamesearched)?$playernamesearched:'' }}">
      </form>
    </div>
    @endcan
  </div>
  </div>
</div>

resources/views/player/partials/menu.blade.php
<aside class="main-sidebar sidebar-light-info elevation-4" style="min-height: 917px;">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img style="width:100%;max-width:250px;padding:5%" image_height="147" image_id="1410" title="my-padel-rating-ranking-paddle-mundial" src="https://mypadelrating.com/wp-content/uploads/2020/09/my-padel-rating-ranking-paddle-mundial.png" class="img-responsive wp-image-1410" srcset="https://mypadelrating.com/wp-content/uploads/2020/09/my-padel-rating-ranking-paddle-mundial-200x84.png 200w, https://mypadelrating.com/wp-content/uploads/2020/09/my-padel-rating-ranking-paddle-mundial.png 350w" sizes="(max-width: 1100px) 100vw, (max-width: 1100px) 100vw, 350px">
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route("player.home") }}">
                        <i class="fas fa-fw fa-tachometer-alt nav-icon">
                        </i>
                        <p>
                            Inicio
                        </p>
                    </a>
                </li>
                
                @can('club_access')
                    <li class="nav-item">
                        <a href="{{ route("player.clubs.index") }}" class="nav-link {{ request()->is("admin/clubs") || request()->is("admin/clubs/*") ? "active" : "" }}">
                            <i class="fa-fw nav-icon fas fa-cogs">

                            </i>
                            <p>
                                Clubes
                            </p>
                        </a>
                    </li>
                @endcan
                @can('tournament_access')
                    <li class="nav-item">
                        <a href="{{ route("player.tournaments.index") }}" class="nav-link {{ request()->is("admin/tournaments") || request()->is("admin/tournaments/*") ? "active" : "" }}">
                            <i class="fa-fw nav-icon fas fa-cogs">

                            </i>
                            <p>
                                Torneos
                            </p>
                        </a>
                    </li>
                @endcan
                @can('player_access')
                    <li class="nav-item">
                        <a href="{{ route("player.players.index") }}" class="nav-link {{ request()->is("admin/players") || request()->is("admin/players/*") ? "active" : "" }}">
                            <i class="fa-fw nav-icon fas fa-cogs">

                            </i>
                            <p>
                                Jugadores
                            </p>
                        </a>
                    </li>
                @endcan
                @can('score_access')
                    <li class="nav-item">
                        <a href="{{ route("player.scores.index") }}" class="nav-link {{ request()->is("admin/scores") || request()->is("admin/scores/*") ? "active" : "" }}">
                            <i class="fa-fw nav-icon fas fa-cogs">

                            </i>
                            <p>
                                Registra un resultado
                            </p>
                        </a>
                    </li>
                @endcan
                @php($unread = \App\Models\QaTopic::unreadCount())
                    <li class="nav-item">
                        <a href="{{ route("player.messenger.index") }}" class="{{ request()->is("admin/messenger") || request()->is("admin/messenger/*") ? "active" : "" }} nav-link">
                            <i class="fa-fw fa fa-envelope nav-icon">

                            </i>
                            <p>{{ trans('global.messages') }}</p>
                            @if($unread > 0)
                                <strong>( {{ $unread }} )</strong>
                            @endif

                        </a>
                    </li>
                    @if(file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php')))
                        @can('profile_password_edit')
                            <li class="nav-item">
                                <a class="nav-link {{ request()->is('profile/password') || request()->is('profile/password/*') ? 'active' : '' }}" href="{{ route('profile.password.edit') }}">
                                    <i class="fa-fw fas fa-key nav-icon">
                                    </i>
                                    <p>
                                        {{ trans('global.change_password') }}
                                    </p>
                                </a>
                            </li>
                        @endcan
                    @endif
                    <li class="nav-item">
                        <a href="#" class="nav-link" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                            <p>
                                <i class="fas fa-fw fa-sign-out-alt nav-icon">

                                </i>
                                <p>{{ trans('global.logout') }}</p>
                            </p>
                        </a>
                    </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>