routes/web.php
<?php

Route::redirect('/', '/login');

// Horarios
Route::resource('schedule' , 'ScheduleController');

Route::get('/home', function () {
    $user = Auth::user();
    $roles = $user->roles()->get();
    foreach ($roles as $role) {
        //Jugador
        if ($role->pivot->role_id == 4)
        {
            if (session('status')) {
                return redirect()->route('player.home')->with('status', session('status'));
            }

            return redirect()->route('player.home');
        }
    }
        if (session('status')) {
            return redirect()->route('admin.home')->with('status', session('status'));
        }

        return redirect()->route('admin.home');
});

Auth::routes();
Route::get('userVerification/{token}', 'UserVerificationController@approve')->name('userVerification');

Route::get('sharedplayer/{player}', 'ShareController@getPlayer')->name('sharedplayer');

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'adminroute']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Questions
    Route::delete('questions/destroy', 'QuestionsController@massDestroy')->name('questions.massDestroy');
    Route::resource('questions', 'QuestionsController');
    
    // Clubs
    Route::delete('clubs/destroy', 'ClubsController@massDestroy')->name('clubs.massDestroy');
    Route::post('clubs/parse-csv-import', 'ClubsController@parseCsvImport')->name('clubs.parseCsvImport');
    Route::post('clubs/process-csv-import', 'ClubsController@processCsvImport')->name('clubs.processCsvImport');
    Route::resource('clubs', 'ClubsController');

    // Tournaments
    Route::delete('tournaments/destroy', 'TournamentsController@massDestroy')->name('tournaments.massDestroy');
    Route::post('tournaments/parse-csv-import', 'TournamentsController@parseCsvImport')->name('tournaments.parseCsvImport');
    Route::post('tournaments/process-csv-import', 'TournamentsController@processCsvImport')->name('tournaments.processCsvImport');
    Route::resource('tournaments', 'TournamentsController');

    // Players
    Route::delete('players/destroy', 'PlayersController@massDestroy')->name('players.massDestroy');
    Route::post('players/parse-csv-import', 'PlayersController@parseCsvImport')->name('players.parseCsvImport');
    Route::post('players/process-csv-import', 'PlayersController@processCsvImport')->name('players.processCsvImport');
    Route::resource('players', 'PlayersController');

    // Scores
    Route::delete('scores/destroy', 'ScoresController@massDestroy')->name('scores.massDestroy');
    Route::post('scores/parse-csv-import', 'ScoresController@parseCsvImport')->name('scores.parseCsvImport');
    Route::post('scores/process-csv-import', 'ScoresController@processCsvImport')->name('scores.processCsvImport');
    Route::resource('scores', 'ScoresController');

    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');

   
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

Route::group(['prefix' => 'player', 'as' => 'player.', 'namespace' => 'Player', 'middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('linkplayer/{id}', 'HomeController@getLinkPlayer')->name('linkplayer');
    Route::get('firstquestionary', 'HomeController@getFirstQuestionary')->name('firstquestionary');
    Route::post('firstquestionary', 'HomeController@postFirstQuestionary')->name('savefirstquestionary');
    Route::post('saveuserlocation', 'HomeController@postSaveUserLocation')->name('saveuserlocation');

    Route::get('player/{id}', 'PlayersController@getPlayer')->name('player');
    Route::get('myplayer', 'PlayersController@getMyPlayer')->name('myplayer');
    Route::post('myprofile', 'PlayersController@postMyProfile')->name('savemyprofile');

    Route::get('playerinfo/{player}', 'PlayersController@getPlayerinfo')->name('playerinfo');
    
    Route::get('searchplayers', 'HomeController@getSearchPlayers')->name('getsearchplayers');
    Route::post('searchplayers', 'HomeController@postSearchPlayers')->name('searchplayers');
    Route::post('search', 'HomeController@search')->name('search');

    // Clubs
    Route::delete('clubs/destroy', 'ClubsController@massDestroy')->name('clubs.massDestroy');
    Route::resource('clubs', 'ClubsController');

    // Tournaments
    Route::delete('tournaments/destroy', 'TournamentsController@massDestroy')->name('tournaments.massDestroy');
    Route::resource('tournaments', 'TournamentsController');

    // Players
    Route::delete('players/destroy', 'PlayersController@massDestroy')->name('players.massDestroy');
    Route::resource('players', 'PlayersController');

    // Scores
    Route::delete('scores/destroy', 'ScoresController@massDestroy')->name('scores.massDestroy');
    Route::get('scores/verify/{score}', 'ScoresController@getVerifyScore')->name('scores.verify');
    Route::get('scores/confirmunverify/{score}', 'ScoresController@getConfirmUnverifyScore')->name('scores.confirmunverify');
    Route::get('scores/confirmverify/{score}', 'ScoresController@getConfirmVerifyScore')->name('scores.confirmverify');
    Route::resource('scores', 'ScoresController');

    //Messenger
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');

    Route::get('messenger/conversation/{player}', 'MessengerController@getConversation')->name('messenger.conversation');
});

app/Http/Controllers/Admin/MessengerController.php
<?php
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\QaTopicCreateRequest;
use App\Http\Requests\QaTopicReplyRequest;
use App\Models\QaTopic;
use App\Models\User;
use Auth;
use Carbon\Carbon;
use Illuminate\Http\Request;

class MessengerController extends Controller
{
    public function index()
    {
        $topics = QaTopic::where(function ($query) {
            $query
                ->where('creator_id', Auth::id())
                ->orWhere('receiver_id', Auth::id());
        })
            ->orderBy('created_at', 'DESC')
            ->get();

        $title   = trans('global.all_messages');
        $unreads = $this->unreadTopics();

        return view('admin.messenger.index', compact('topics', 'title', 'unreads'));
    }

    public function createTopic()
    {
        $users = User::all()
            ->except(Auth::id());

        $unreads = $this->unreadTopics();

        return view('admin.messenger.create', compact('users', 'unreads'));
    }

    public function storeTopic(QaTopicCreateRequest $request)
    {
        $topic = QaTopic::create([
            'subject'     => $request->input('subject'),
            'creator_id'  => Auth::id(),
            'receiver_id' => $request->input('recipient'),
        ]);

        $topic->messages()->create([
            'sender_id' => Auth::id(),
            'content'   => $request->input('content'),
        ]);

        return redirect()->route('admin.messenger.index');
    }

    public function showMessages(QaTopic $topic)
    {
        $this->checkAccessRights($topic);

        foreach ($topic->messages as $message) {
            if ($message->sender_id !== Auth::id() && $message->read_at === null) {
                $message->read_at = Carbon::now();
                $message->save();
            }
        }

        $unreads = $this->unreadTopics();

        return view('admin.messenger.show', compact('topic', 'unreads'));
    }

    public function destroyTopic(QaTopic $topic)
    {
        $this->checkAccessRights($topic);

        $topic->delete();

        return redirect()->route('admin.messenger.index');
    }

    public function showInbox()
    {
        $title = trans('global.inbox');

        $topics = QaTopic::where('receiver_id', Auth::id())
            ->orderBy('created_at', 'DESC')
            ->get();

        $unreads = $this->unreadTopics();

        return view('admin.messenger.index', compact('topics', 'title', 'unreads'));
    }

    public function showOutbox()
    {
        $title = trans('global.outbox');

        $topics = QaTopic::where('creator_id', Auth::id())
            ->orderBy('created_at', 'DESC')
            ->get();

        $unreads = $this->unreadTopics();

        return view('admin.messenger.index', compact('topics', 'title', 'unreads'));
    }

    public function replyToTopic(QaTopicReplyRequest $request, QaTopic $topic)
    {
        $this->checkAccessRights($topic);

        $topic->messages()->create([
            'sender_id' => Auth::id(),
            'content'   => $request->input('content'),
        ]);

        return redirect()->route('admin.messenger.index');
    }

    public function showReply(QaTopic $topic)
    {
        $this->checkAccessRights($topic);

        $receiverOrCreator = $topic->receiverOrCreator();

        if ($receiverOrCreator === null || $receiverOrCreator->trashed()) {
            abort(404);
        }

        $unreads = $this->unreadTopics();

        return view('admin.messenger.reply', compact('topic', 'unreads'));
    }

    public function unreadTopics(): array
    {
        $topics = QaTopic::where(function ($query) {
            $query
                ->where('creator_id', Auth::id())
                ->orWhere('receiver_id', Auth::id());
        })
            ->with('messages')
            ->orderBy('created_at', 'DESC')
            ->get();

        $inboxUnreadCount  = 0;
        $outboxUnreadCount = 0;

        foreach ($topics as $topic) {
            foreach ($topic->messages as $message) {
                if ($message->sender_id !== Auth::id()
                    && $message->read_at === null
                ) {
                    if ($topic->creator_id !== Auth::id()) {
                        $inboxUnreadCount++;
                    } else {
                        $outboxUnreadCount++;
                    }
                }
            }
        }

        return [
            'inbox'  => $inboxUnreadCount,
            'outbox' => $outboxUnreadCount,
        ];
    }

    private function checkAccessRights(QaTopic $topic)
    {
        $user = Auth::user();

        if ($topic->creator_id !== $user->id && $topic->receiver_id !== $user->id) {
            return abort(401);
        }
    }
}

app/Http/Controllers/Admin/PlayersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyPlayerRequest;
use App\Http\Requests\StorePlayerRequest;
use App\Http\Requests\UpdatePlayerRequest;
use App\Models\Player;
use App\Models\User;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class PlayersController extends Controller
{
    use CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('player_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = Player::with(['user'])->select(sprintf('%s.*', (new Player)->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate      = 'player_show';
                $editGate      = 'player_edit';
                $deleteGate    = 'player_delete';
                $crudRoutePart = 'players';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : "";
            });
            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : "";
            });
            $table->editColumn('surname', function ($row) {
                return $row->surname ? $row->surname : "";
            });
            $table->editColumn('genre', function ($row) {
                return $row->genre ? Player::GENRE_SELECT[$row->genre] : '';
            });

            $table->editColumn('license_number', function ($row) {
                return $row->license_number ? $row->license_number : "";
            });
            $table->addColumn('user_email', function ($row) {
                return $row->user ? $row->user->email : '';
            });

            $table->rawColumns(['actions', 'placeholder', 'user']);

            return $table->make(true);
        }

        return view('admin.players.index');
    }

    public function create()
    {
        abort_if(Gate::denies('player_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('email', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.players.create', compact('users'));
    }

    public function store(StorePlayerRequest $request)
    {
        $player = Player::create($request->all());

        return redirect()->route('admin.players.index');
    }

    public function edit(Player $player)
    {
        abort_if(Gate::denies('player_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('email', 'id')->prepend(trans('global.pleaseSelect'), '');

        $player->load('user');

        return view('admin.players.edit', compact('users', 'player'));
    }

    public function update(UpdatePlayerRequest $request, Player $player)
    {
        $player->update($request->all());

        return redirect()->route('admin.players.index');
    }

    public function show(Player $player)
    {
        abort_if(Gate::denies('player_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $player->load('user', 'team1Player1Scores', 'team1Player2Scores', 'team2Player1Scores', 'team2Player2Scores');

        return view('admin.players.show', compact('player'));
    }

    public function destroy(Player $player)
    {
        abort_if(Gate::denies('player_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $player->delete();

        return back();
    }

    public function massDestroy(MassDestroyPlayerRequest $request)
    {
        Player::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/player/messenger/conversation.blade.php
@extends('layouts.player')
@section('content')
<!-- Barra superior / buscador -->
<div class="topnavMensajes dropdown">
  <div class="row">
    <div class="col-2">
        <a href="{{ route('player.messenger.showInbox') }}"><i class='fa fa-angle-left atrasIcono'></i></a>
    </div>
    <div class="col-8">
            <div class="mensaje-foto" style="background-size: cover;background-image: url('{{ $player->avatar? '/avatars/'.$player->avatar : '/resources/persona.png' }}')"></div>
            <h5 class="nombreContacto">{{ $player->name }} {{ $player->surname }}</h5>
    </div>
    <div class="col-2">
        <button class="fa fa-ellipsis-v myElipsis" type="button" data-toggle="dropdown" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu" style="margin-right: 120px;">
          <li class="dropdown-header">Opciones</li>
          <li><a href="#">Compartir ubicación</a></li>
          <li><a href="#">Borrar conversación</a></li>
          <li><a href="#">Bloquear usuario</a></li>
          <li class="divider"></li>
        </ul>
    </div>
  </div>
</div>

<!-- Fecha -->
<div class="row">
    <label class="labelFecha">{{ $topic->created_at }}</label>
</div>

<!-- Mensajes -->
<div class="col-12 contenedorMensajes">
    @foreach ($topic->messages as $message)
    <div class="col-10 mensaje {{ (($message->sender_id==$player->id)?'otro':'tu') }}">
        <p>{{ $message->content }}</p>
        <label class="hora">{{ $message->created_at }}</label>
    </div>
    @endforeach
</div>

<div class="hacerEspacio" style="height: 120px">
    &nbsp
<div>
<nav class="botnav fixed-bottom" style="bottom: 60px;">
    <div class="row" style="margin-inline: 10px;">
        <form action="{{ route('player.messenger.reply', [$topic->id]) }}" method="POST" style="width:100%">
            @csrf
            <input class="escribirTexto col-10" type="text" placeholder="Escribe tu mensaje..." name="content">
            <button type="submit" class="btn fa fa-angle-double-right btnEnviarMensaje"></button>
        </form>
    </div>
</nav>
@endsection

@section('scripts')
@parent
<script type="text/javascript">
window.setTimeout(function () {
  window.location.reload();
}, 30000);
window.setTimeout(function () {
  window.scrollTo(0,document.body.scrollHeight);
}, 1000);
</script>
@endsection

resources/views/player/messenger/create.blade.php
@extends('admin.messenger.template')

@section('title', trans('global.new_message'))

@section('messenger-content')
<div class="row">
    <div class="col-md-12">
        <form action="{{ route("admin.messenger.storeTopic") }}" method="POST">
            @csrf
            <div class="card card-default">
                <div class="card-body">
                    <div class="row">

                        <div class="col-lg-12 form-group">
                            <label for="recipient" class="control-label">
                                {{ trans('global.recipient') }}
                            </label>
                            <select name="recipient" class="form-control">
                                @foreach($users as $user)
                                    <option value="{{ $user->id }}">{{ $user->email }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="col-lg-12 form-group">
                            <label for="subject" class="control-label">
                                {{ trans('global.subject') }}
                            </label>
                            <input type="text" name="subject" class="form-control" />
                        </div>

                        <div class="col-lg-12 form-group">
                            <label for="content" class="control-label">
                                {{ trans('global.content') }}
                            </label>
                            <textarea name="content" class="form-control"></textarea>
                        </div>
                    </div>
                    <input type="submit" value="{{ trans('global.submit') }}" class="btn btn-success" />
                </div>
            </div>
        </form>
    </div>
</div>
@stop

resources/views/player/messenger/index.blade.php
@extends('layouts.player')
@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="list-group">
            @php($myplayer_id = \Auth::user()->userPlayers()->first()->id)
            @forelse($topics as $topic)
                @php($otherplayer_id = ($topic->creator_id==$myplayer_id)?$topic->receiver_id:$topic->creator_id)
                @php($otherplayer = \App\Models\Player::find($otherplayer_id))
                <div class="row list-group-item d-flex">
                    <div class="col-5">
                        <a href="{{ route('player.messenger.conversation', [$otherplayer_id]) }}">
                                @if($topic->hasUnreads())
                                    <strong>
                                        {{ $otherplayer !== null ? $otherplayer->name." ".$otherplayer->surname : '' }}
                                    </strong>
                                @else
                                    {{ $otherplayer !== null ? $otherplayer->name." ".$otherplayer->surname : '' }}
                                @endif
                        </a>
                    </div>
                    <div class="col-4 text-right">{{ $topic->created_at->diffForHumans() }}</div>
                    <div class="col-2 text-center">
                        <form action="{{ route('player.messenger.destroyTopic', [$topic->id]) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');">
                            <input type="hidden" name="_method" value="DELETE">
                            @csrf
                            <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                        </form>
                    </div>
                </div>
                @empty
                <div class="row list-group-item">
                    {{ trans('global.you_have_no_messages') }}
                </div>
            @endforelse
        </div>
    </div>
</div>
@endsection

resources/views/player/messenger/reply.blade.php
@extends('admin.messenger.template')

@section('title', trans('global.new_message'))

@section('messenger-content')

<div class="row">
    <div class="col-lg-12">
        <form action="{{ route("admin.messenger.reply", [$topic->id]) }}" method="POST">
            @csrf
            <div class="card card-default">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-12 form-group">
                            <label for="content" class="control-label">
                                {{ trans('global.content') }}
                            </label>
                            <textarea name="content" class="form-control"></textarea>
                        </div>
                    </div>
                    <input type="submit" value="{{ trans('global.reply') }}" class="btn btn-success" />
                </div>
            </div>
        </form>
    </div>
</div>
@stop

resources/views/player/messenger/show.blade.php
@extends('admin.messenger.template')

@section('title', $topic->subject)

@section('messenger-content')
<div class="row">
    <p>
        @if($topic->receiverOrCreator() !== null && !$topic->receiverOrCreator()->trashed())
            <a href="{{ route('admin.messenger.reply', [$topic->id]) }}" class="btn btn-primary">
                {{ trans('global.reply') }}
            </a>
        @endif
    </p>
    <div class="col-lg-12">
        <div class="list-group">
            @foreach($topic->messages as $message)
                <div class="row list-group-item">
                    <div class="row">
                        <div class="col col-lg-10">
                            <strong>{{ $message->sender->email }}</strong>
                        </div>
                        <div class="col col-lg-2">
                            {{ $message->created_at->diffForHumans() }}
                        </div>
                    </div>
                    <div>
                    </div>
                    <div class="row">
                        <div class="col col-lg-12">
                            {{ $message->content }}
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>
@endsection

resources/views/player/messenger/template.blade.php
@extends('layouts.admin')

@section('content')
<div class="content">
    <div class="row">
        <p class="col-lg-12">
            @yield('title')
        </p>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <p>
                <a href="{{ route('admin.messenger.createTopic') }}" class="btn btn-primary btn-block">
                    {{ trans('global.new_message') }}
                </a>
            </p>
            <div class="list-group">
                <a href="{{ route('admin.messenger.index') }}" class="list-group-item">
                    {{ trans('global.all_messages') }}
                </a>
                <a href="{{ route('admin.messenger.showInbox') }}" class="list-group-item">
                    @if($unreads['inbox'] > 0)
                        <strong>
                            {{ trans('global.inbox') }}
                            ({{ $unreads['inbox'] }})
                        </strong>
                    @else
                        {{ trans('global.inbox') }}
                    @endif
                </a>
                <a href="{{ route('admin.messenger.showOutbox') }}" class="list-group-item">
                    @if($unreads['outbox'] > 0)
                        <strong>
                            {{ trans('global.outbox') }}
                            ({{ $unreads['outbox'] }})
                        </strong>
                    @else
                        {{ trans('global.outbox') }}
                    @endif
                </a>
            </div>
        </div>
        <div class="col-lg-9">
            @yield('messenger-content')
        </div>
    </div>
</div>
@stop